import type { Metadata } from "next";
import { Inter, Orbitron, Righteous } from "next/font/google";
import "./globals.css";

const righteous = Righteous({
	weight: "400",
	subsets: ["latin"],
	variable: "--font-righteous",
	display: "swap",
});

const orbitron = Orbitron({
	weight: "400",
	subsets: ["latin"],
	variable: "--font-orbitron",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${righteous.variable} ${orbitron.variable}`}>
				{children}
			</body>
		</html>
	);
}
